### ISSUE TITLE
時間計算

### ISSUE THREAD

**Issue by hurikku** [OUCC/calculator2022#10]
時間の単位変換を行います。
単位はとりあえずw,d,h,m,s（週、日、時間、分、秒）でやっていきます。

**Comment by yu195** [comment]
それぞれ変換する関数を用意するよりw,d,h,m,sのプロパティを持つクラスを定義してコンストラクタを増やすほうがいいと思います。

**Comment by yu195** [comment]
こんな感じでTimeSpanクラスを作ればいいと思う
https://docs.microsoft.com/ja-jp/dotnet/api/system.timespan?view=net-6.0
