### ISSUE TITLE
JSONで保存するためのデータモデルの作成

### ISSUE THREAD

**Issue by yu195** [OUCC/calculator2022#23]
必要なのは
- id: int
- formula: string 何らかの区切り文字で区切られた式
- result: double 結果
- createdDate: DateTime 計算した日
- toList(): formulaを区切り文字に従って分離する関数
- Map<String,dynamic> toJson(): JSON用のMapに変換
- fromJson(Map<String,dynamic>)コンストラクタ: JSON用のMapから変換する。

全てのフィールドにfinalをつけてイミュータブルにする

**Comment by Arei1126** [comment]
クラス名何にするのが適当でしょう
