### ISSUE TITLE
SharedPreferencesを使ってデータを保存

### ISSUE THREAD

**Issue by yu195** [OUCC/calculator2022#24]
キー用の列挙型とそれの値をとる拡張関数の追加
拡張する関数は以下の通り
```dart
String get name => this.toString().split(".").last;
```

下のものを参考にJSONリストの入出力を追加する。
https://qiita.com/mamoru_takami/items/2d930ee927c048060741

**Comment by yu195** [comment]
https://note.com/hatchoutschool/n/n3a7c6ae218fa

**Comment by Arei1126** [comment]
最終的な保存の形が見えません
例えば、
(key, List<String>)で、
savedata1:(1, 2+3 ,5 ,2021/5/2)
savedata2:(2, 2+5 ,7 ,2021/5/2)・・・みたいな感じでしょうか

**Comment by Arei1126** [comment]
列挙型のキーは、sharedPreference用のキーということですよね

**Comment by yu195** [comment]
グローバル変数でメモリ上のデータは保持します。
```dart
ResultData[] resultData = [];
```
ですが今回作る関数は以下の通り引数からそれを受け取ります。どのように渡すかはあとで考えても大丈夫です。
```dart
void saveResultDataList(List<ResultData>);
List<ResultData> loadResultDataList();
```

**Comment by Arei1126** [comment]
1.キー用の列挙型はMap型のjsonを作るときに使うキーって事で合ってますか？
2.Stringをsharedprefで保存するとsharedpref用のキーどうするの問題が出ると思います。それならばmapからsharedprefに保存するような関数にして、"id"をsharedpref用のキーにするのは如何でしょうか

**Comment by yu195** [comment]
1. あっています
2. キーをどうするかという問題ですが1つのkeyに対して`List<String>`型のvalueも入れられるので問題ないと思います。
https://pub.dev/documentation/shared_preferences/latest/shared_preferences/SharedPreferences/setStringList.html

このような感じで行けると思います。
```dart
final prefs = await SharedPreferences.getInstance();
await prefs.setStringList("key", resultDataList.map(d => json.encode(d.toJson())).toList());
```

**Comment by Arei1126** [comment]
1は了解しました。2は説明不足でごめんなさい。作る関数を、Stringを引数として取るだけだとsharedprefで保存する際のキーをどうするのかという問題です。valueをStringの配列で格納するのは了承してます。上記の例のようにMapを引数にして、String配列としてを格納する関数でOKだと思うのですが、その際のKeyはどうしようか、それならばMapのなかのidの値をsharedprefで保存する際のkeyにしようではないか、という話です

**Comment by yu195** [comment]
キーは配列の要素に対して与えるのではなく配列全体に与えるので１つあれば十分ですし、idは1つのvalueに複数含まれ、さらに計算を行うごとに変動します。この関数はResultDataの保存にしか使わないのでキーは引数にとる必要はありません。キーの名前について悩んでいるのでしたら、`result_data`などはどうでしょう？

**Comment by Arei1126** [comment]
計算の履歴を残すのならformulaも必要ではないでしょうか？てっきり、Map(json)にある全ての値(id,formula,result,created_date)を履歴として残していくために、sharedPreferenceを使うものだと思っていたのですが・・・

**Comment by Arei1126** [comment]
キーのやつ、もうこれグローバルで
Map<String, String> JsonKeyNames = {
  "id": "id",
  "formula": "formula",
  "result": "result"
  "createdDate": "created_date"
  }
を宣言するのと何が違うのかよくわからなくなってきました

**Comment by yu195** [comment]
一度jsonにしたものを見てみてください。jsonはただのStringですがオブジェクトが入ってるはずです。
