### ISSUE TITLE
TimeSpanクラスの作成

### ISSUE THREAD

**Issue by yu195** [OUCC/calculator2022#28]
- [ ] フィールド
- `final int fullMilliSec` 1ミリ秒単位で記録する。ミリで設定しても最大値は106,751,991,167日になるらしい
- [ ] パブリックなgetter
- `day int` 日にちを取得
- `hour int` 時間を取得 (最大値24)
- `minute int` 分を取得 (最大値60)
- `second int` 秒を取得 (最大値60)
- `milliSec int` ミリ秒取得 (最大値1000)
- [ ] コンストラクタ
- `TimeSpan({int? day, int? hour, int? minute, double? second})` 名前付き引数利用して使われたものだけで初期化できるようにする
- `TimeSpan.fromMilliSec(int)` ミリ秒から生成
- `TimeSpan.fromString(String)` discordで話していた形式で書いたときにparseできるようにする
- [ ] 演算子のオーバーライド
- `TimeSpan operator +(TimeSpan)`
- `TimeSpan operator -(TimeSpan)`
- `TimeSpan operator *(num)`
- `TimeSpan operator /(num)`
- `bool operator ==(TimeSpan)`
- `int get hashCode`

暇があったら以下のfull付きのものも実装してください。それぞれ上のものから最大値を取り払ったものです。
- `fullDay double`
- `fullHour double`
- `fullMinute double`
- `fullSecond double`

**Comment by hurikku** [comment]
コンストラクタで受け取った値をfinal int fullMilliSecにぶち込んで他の部分で使う方法が分からなかったのでいまのとこfullMilliSecはfinalではなくカプセル化してるだけです
ついでにfullMilliSecのgetterも作っときます

**Comment by hurikku** [comment]
関数として機能を作り直すのでissue立て直します
